#!/bin/bash
NAME=fraud-detection
DIR=/home/udoko/fintech_project/fraud_detection/api
USER=udoko
GROUP=udoko
WORKERS=3
WORKER_CLASS=uvicorn.workers.UvicornWorker
VENV=$DIR/.venv/bin/activate
BIND=127.0.0.1:8000
LOG_LEVEL=error
LOG_FILE=$DIR/logs/gunicorn.log  # Add this line for Gunicorn logs

cd $DIR
source $VENV
pip list > $DIR/logs/installed_libraries.txt

# Add these lines for debugging
echo "Current working directory: $(pwd)" >> $LOG_FILE
echo "Activated virtual environment: $VENV" >> $LOG_FILE
echo "Python executable: $(which python)" >> $LOG_FILE
echo "PATH: $PATH" >> $LOG_FILE

exec /home/udoko/.local/bin/gunicorn main:app \
  --name $NAME \
  --workers $WORKERS \
  --worker-class $WORKER_CLASS \
  --user=$USER \
  --group=$GROUP \
  --bind=$BIND \
  --log-level=$LOG_LEVEL \
  --log-file=$LOG_FILE  # Specify the log file for Gunicorn
  --pythonpath=$DIR
